# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

os:
  - linux

r:
  - oldrel
  - release
  - devel

r_packages:
  - covr
  - eha

after_success:
  - travis_wait 20 Rscript -e "covr::codecov()"
