language: r
r:
  - oldrel
  - release
  - devel

cache: packages

os:
  - linux
  - osx

r:
  - oldrel
  - release
  - devel

r_packages:
  - covr
  - eha

after_success:
  - travis_wait 20 Rscript -e "covr::codecov()"
