# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

os:
  - linux

r:
  - oldrel
  - release
  - devel

install:
  - Rscript -e "if (!require('devtools')) install.packages('devtools')"
  - Rscript -e "devtools::install_deps(dep = TRUE)"

cran: http://cran.rstudio.com
repos:
  CRAN: http://cran.rstudio.com

r_packages:
  - covr
  - eha

after_success:
  - travis_wait 20 Rscript -e "covr::codecov()"
